// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service_push.proto

package com.neusoft.grpc.proto.demo1;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string topicName = 1;</code>
   */
  java.lang.String getTopicName();
  /**
   * <code>string topicName = 1;</code>
   */
  com.google.protobuf.ByteString
      getTopicNameBytes();

  /**
   * <code>string status = 2;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 2;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>bytes message = 3;</code>
   */
  com.google.protobuf.ByteString getMessage();
}
