// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service_push.proto

package com.neusoft.grpc.proto.demo1;

public interface StatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Status)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string status = 1;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 1;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
