// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service_push.proto

package com.neusoft.grpc.proto.demo1;

/**
 * <pre>
 *订阅信息
 * </pre>
 *
 * Protobuf type {@code TopicInfo}
 */
public  final class TopicInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:TopicInfo)
    TopicInfoOrBuilder {
  // Use TopicInfo.newBuilder() to construct.
  private TopicInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TopicInfo() {
    topicName_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private TopicInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.neusoft.grpc.proto.demo1.ClientInfo.Builder subBuilder = null;
            if (clientInfo_ != null) {
              subBuilder = clientInfo_.toBuilder();
            }
            clientInfo_ = input.readMessage(com.neusoft.grpc.proto.demo1.ClientInfo.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(clientInfo_);
              clientInfo_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            topicName_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.neusoft.grpc.proto.demo1.ServicePushDemo.internal_static_TopicInfo_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.neusoft.grpc.proto.demo1.ServicePushDemo.internal_static_TopicInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.neusoft.grpc.proto.demo1.TopicInfo.class, com.neusoft.grpc.proto.demo1.TopicInfo.Builder.class);
  }

  public static final int CLIENTINFO_FIELD_NUMBER = 1;
  private com.neusoft.grpc.proto.demo1.ClientInfo clientInfo_;
  /**
   * <code>.ClientInfo clientInfo = 1;</code>
   */
  public boolean hasClientInfo() {
    return clientInfo_ != null;
  }
  /**
   * <code>.ClientInfo clientInfo = 1;</code>
   */
  public com.neusoft.grpc.proto.demo1.ClientInfo getClientInfo() {
    return clientInfo_ == null ? com.neusoft.grpc.proto.demo1.ClientInfo.getDefaultInstance() : clientInfo_;
  }
  /**
   * <code>.ClientInfo clientInfo = 1;</code>
   */
  public com.neusoft.grpc.proto.demo1.ClientInfoOrBuilder getClientInfoOrBuilder() {
    return getClientInfo();
  }

  public static final int TOPICNAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object topicName_;
  /**
   * <code>string topicName = 2;</code>
   */
  public java.lang.String getTopicName() {
    java.lang.Object ref = topicName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      topicName_ = s;
      return s;
    }
  }
  /**
   * <code>string topicName = 2;</code>
   */
  public com.google.protobuf.ByteString
      getTopicNameBytes() {
    java.lang.Object ref = topicName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      topicName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (clientInfo_ != null) {
      output.writeMessage(1, getClientInfo());
    }
    if (!getTopicNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, topicName_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (clientInfo_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getClientInfo());
    }
    if (!getTopicNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, topicName_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.neusoft.grpc.proto.demo1.TopicInfo)) {
      return super.equals(obj);
    }
    com.neusoft.grpc.proto.demo1.TopicInfo other = (com.neusoft.grpc.proto.demo1.TopicInfo) obj;

    boolean result = true;
    result = result && (hasClientInfo() == other.hasClientInfo());
    if (hasClientInfo()) {
      result = result && getClientInfo()
          .equals(other.getClientInfo());
    }
    result = result && getTopicName()
        .equals(other.getTopicName());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasClientInfo()) {
      hash = (37 * hash) + CLIENTINFO_FIELD_NUMBER;
      hash = (53 * hash) + getClientInfo().hashCode();
    }
    hash = (37 * hash) + TOPICNAME_FIELD_NUMBER;
    hash = (53 * hash) + getTopicName().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.neusoft.grpc.proto.demo1.TopicInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.neusoft.grpc.proto.demo1.TopicInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.neusoft.grpc.proto.demo1.TopicInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.neusoft.grpc.proto.demo1.TopicInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.neusoft.grpc.proto.demo1.TopicInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.neusoft.grpc.proto.demo1.TopicInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.neusoft.grpc.proto.demo1.TopicInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.neusoft.grpc.proto.demo1.TopicInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.neusoft.grpc.proto.demo1.TopicInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.neusoft.grpc.proto.demo1.TopicInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.neusoft.grpc.proto.demo1.TopicInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.neusoft.grpc.proto.demo1.TopicInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.neusoft.grpc.proto.demo1.TopicInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *订阅信息
   * </pre>
   *
   * Protobuf type {@code TopicInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:TopicInfo)
      com.neusoft.grpc.proto.demo1.TopicInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.neusoft.grpc.proto.demo1.ServicePushDemo.internal_static_TopicInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.neusoft.grpc.proto.demo1.ServicePushDemo.internal_static_TopicInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.neusoft.grpc.proto.demo1.TopicInfo.class, com.neusoft.grpc.proto.demo1.TopicInfo.Builder.class);
    }

    // Construct using com.neusoft.grpc.proto.demo1.TopicInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (clientInfoBuilder_ == null) {
        clientInfo_ = null;
      } else {
        clientInfo_ = null;
        clientInfoBuilder_ = null;
      }
      topicName_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.neusoft.grpc.proto.demo1.ServicePushDemo.internal_static_TopicInfo_descriptor;
    }

    public com.neusoft.grpc.proto.demo1.TopicInfo getDefaultInstanceForType() {
      return com.neusoft.grpc.proto.demo1.TopicInfo.getDefaultInstance();
    }

    public com.neusoft.grpc.proto.demo1.TopicInfo build() {
      com.neusoft.grpc.proto.demo1.TopicInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.neusoft.grpc.proto.demo1.TopicInfo buildPartial() {
      com.neusoft.grpc.proto.demo1.TopicInfo result = new com.neusoft.grpc.proto.demo1.TopicInfo(this);
      if (clientInfoBuilder_ == null) {
        result.clientInfo_ = clientInfo_;
      } else {
        result.clientInfo_ = clientInfoBuilder_.build();
      }
      result.topicName_ = topicName_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.neusoft.grpc.proto.demo1.TopicInfo) {
        return mergeFrom((com.neusoft.grpc.proto.demo1.TopicInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.neusoft.grpc.proto.demo1.TopicInfo other) {
      if (other == com.neusoft.grpc.proto.demo1.TopicInfo.getDefaultInstance()) return this;
      if (other.hasClientInfo()) {
        mergeClientInfo(other.getClientInfo());
      }
      if (!other.getTopicName().isEmpty()) {
        topicName_ = other.topicName_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.neusoft.grpc.proto.demo1.TopicInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.neusoft.grpc.proto.demo1.TopicInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.neusoft.grpc.proto.demo1.ClientInfo clientInfo_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.neusoft.grpc.proto.demo1.ClientInfo, com.neusoft.grpc.proto.demo1.ClientInfo.Builder, com.neusoft.grpc.proto.demo1.ClientInfoOrBuilder> clientInfoBuilder_;
    /**
     * <code>.ClientInfo clientInfo = 1;</code>
     */
    public boolean hasClientInfo() {
      return clientInfoBuilder_ != null || clientInfo_ != null;
    }
    /**
     * <code>.ClientInfo clientInfo = 1;</code>
     */
    public com.neusoft.grpc.proto.demo1.ClientInfo getClientInfo() {
      if (clientInfoBuilder_ == null) {
        return clientInfo_ == null ? com.neusoft.grpc.proto.demo1.ClientInfo.getDefaultInstance() : clientInfo_;
      } else {
        return clientInfoBuilder_.getMessage();
      }
    }
    /**
     * <code>.ClientInfo clientInfo = 1;</code>
     */
    public Builder setClientInfo(com.neusoft.grpc.proto.demo1.ClientInfo value) {
      if (clientInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        clientInfo_ = value;
        onChanged();
      } else {
        clientInfoBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.ClientInfo clientInfo = 1;</code>
     */
    public Builder setClientInfo(
        com.neusoft.grpc.proto.demo1.ClientInfo.Builder builderForValue) {
      if (clientInfoBuilder_ == null) {
        clientInfo_ = builderForValue.build();
        onChanged();
      } else {
        clientInfoBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.ClientInfo clientInfo = 1;</code>
     */
    public Builder mergeClientInfo(com.neusoft.grpc.proto.demo1.ClientInfo value) {
      if (clientInfoBuilder_ == null) {
        if (clientInfo_ != null) {
          clientInfo_ =
            com.neusoft.grpc.proto.demo1.ClientInfo.newBuilder(clientInfo_).mergeFrom(value).buildPartial();
        } else {
          clientInfo_ = value;
        }
        onChanged();
      } else {
        clientInfoBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.ClientInfo clientInfo = 1;</code>
     */
    public Builder clearClientInfo() {
      if (clientInfoBuilder_ == null) {
        clientInfo_ = null;
        onChanged();
      } else {
        clientInfo_ = null;
        clientInfoBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.ClientInfo clientInfo = 1;</code>
     */
    public com.neusoft.grpc.proto.demo1.ClientInfo.Builder getClientInfoBuilder() {
      
      onChanged();
      return getClientInfoFieldBuilder().getBuilder();
    }
    /**
     * <code>.ClientInfo clientInfo = 1;</code>
     */
    public com.neusoft.grpc.proto.demo1.ClientInfoOrBuilder getClientInfoOrBuilder() {
      if (clientInfoBuilder_ != null) {
        return clientInfoBuilder_.getMessageOrBuilder();
      } else {
        return clientInfo_ == null ?
            com.neusoft.grpc.proto.demo1.ClientInfo.getDefaultInstance() : clientInfo_;
      }
    }
    /**
     * <code>.ClientInfo clientInfo = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.neusoft.grpc.proto.demo1.ClientInfo, com.neusoft.grpc.proto.demo1.ClientInfo.Builder, com.neusoft.grpc.proto.demo1.ClientInfoOrBuilder> 
        getClientInfoFieldBuilder() {
      if (clientInfoBuilder_ == null) {
        clientInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.neusoft.grpc.proto.demo1.ClientInfo, com.neusoft.grpc.proto.demo1.ClientInfo.Builder, com.neusoft.grpc.proto.demo1.ClientInfoOrBuilder>(
                getClientInfo(),
                getParentForChildren(),
                isClean());
        clientInfo_ = null;
      }
      return clientInfoBuilder_;
    }

    private java.lang.Object topicName_ = "";
    /**
     * <code>string topicName = 2;</code>
     */
    public java.lang.String getTopicName() {
      java.lang.Object ref = topicName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        topicName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string topicName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTopicNameBytes() {
      java.lang.Object ref = topicName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        topicName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string topicName = 2;</code>
     */
    public Builder setTopicName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      topicName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string topicName = 2;</code>
     */
    public Builder clearTopicName() {
      
      topicName_ = getDefaultInstance().getTopicName();
      onChanged();
      return this;
    }
    /**
     * <code>string topicName = 2;</code>
     */
    public Builder setTopicNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      topicName_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:TopicInfo)
  }

  // @@protoc_insertion_point(class_scope:TopicInfo)
  private static final com.neusoft.grpc.proto.demo1.TopicInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.neusoft.grpc.proto.demo1.TopicInfo();
  }

  public static com.neusoft.grpc.proto.demo1.TopicInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TopicInfo>
      PARSER = new com.google.protobuf.AbstractParser<TopicInfo>() {
    public TopicInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new TopicInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TopicInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TopicInfo> getParserForType() {
    return PARSER;
  }

  public com.neusoft.grpc.proto.demo1.TopicInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

