// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service_push.proto

package com.neusoft.grpc.proto.demo1;

/**
 * <pre>
 *主题1
 * </pre>
 *
 * Protobuf type {@code TopicOne}
 */
public  final class TopicOne extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:TopicOne)
    TopicOneOrBuilder {
  // Use TopicOne.newBuilder() to construct.
  private TopicOne(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TopicOne() {
    topicId_ = "";
    topicName_ = "";
    xxx_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private TopicOne(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            topicId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            topicName_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            xxx_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.neusoft.grpc.proto.demo1.ServicePushDemo.internal_static_TopicOne_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.neusoft.grpc.proto.demo1.ServicePushDemo.internal_static_TopicOne_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.neusoft.grpc.proto.demo1.TopicOne.class, com.neusoft.grpc.proto.demo1.TopicOne.Builder.class);
  }

  public static final int TOPICID_FIELD_NUMBER = 1;
  private volatile java.lang.Object topicId_;
  /**
   * <code>string topicId = 1;</code>
   */
  public java.lang.String getTopicId() {
    java.lang.Object ref = topicId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      topicId_ = s;
      return s;
    }
  }
  /**
   * <code>string topicId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getTopicIdBytes() {
    java.lang.Object ref = topicId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      topicId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOPICNAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object topicName_;
  /**
   * <code>string topicName = 2;</code>
   */
  public java.lang.String getTopicName() {
    java.lang.Object ref = topicName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      topicName_ = s;
      return s;
    }
  }
  /**
   * <code>string topicName = 2;</code>
   */
  public com.google.protobuf.ByteString
      getTopicNameBytes() {
    java.lang.Object ref = topicName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      topicName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int XXX_FIELD_NUMBER = 3;
  private volatile java.lang.Object xxx_;
  /**
   * <code>string xxx = 3;</code>
   */
  public java.lang.String getXxx() {
    java.lang.Object ref = xxx_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      xxx_ = s;
      return s;
    }
  }
  /**
   * <code>string xxx = 3;</code>
   */
  public com.google.protobuf.ByteString
      getXxxBytes() {
    java.lang.Object ref = xxx_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      xxx_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getTopicIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, topicId_);
    }
    if (!getTopicNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, topicName_);
    }
    if (!getXxxBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, xxx_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getTopicIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, topicId_);
    }
    if (!getTopicNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, topicName_);
    }
    if (!getXxxBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, xxx_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.neusoft.grpc.proto.demo1.TopicOne)) {
      return super.equals(obj);
    }
    com.neusoft.grpc.proto.demo1.TopicOne other = (com.neusoft.grpc.proto.demo1.TopicOne) obj;

    boolean result = true;
    result = result && getTopicId()
        .equals(other.getTopicId());
    result = result && getTopicName()
        .equals(other.getTopicName());
    result = result && getXxx()
        .equals(other.getXxx());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TOPICID_FIELD_NUMBER;
    hash = (53 * hash) + getTopicId().hashCode();
    hash = (37 * hash) + TOPICNAME_FIELD_NUMBER;
    hash = (53 * hash) + getTopicName().hashCode();
    hash = (37 * hash) + XXX_FIELD_NUMBER;
    hash = (53 * hash) + getXxx().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.neusoft.grpc.proto.demo1.TopicOne parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.neusoft.grpc.proto.demo1.TopicOne parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.neusoft.grpc.proto.demo1.TopicOne parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.neusoft.grpc.proto.demo1.TopicOne parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.neusoft.grpc.proto.demo1.TopicOne parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.neusoft.grpc.proto.demo1.TopicOne parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.neusoft.grpc.proto.demo1.TopicOne parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.neusoft.grpc.proto.demo1.TopicOne parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.neusoft.grpc.proto.demo1.TopicOne parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.neusoft.grpc.proto.demo1.TopicOne parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.neusoft.grpc.proto.demo1.TopicOne parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.neusoft.grpc.proto.demo1.TopicOne parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.neusoft.grpc.proto.demo1.TopicOne prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *主题1
   * </pre>
   *
   * Protobuf type {@code TopicOne}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:TopicOne)
      com.neusoft.grpc.proto.demo1.TopicOneOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.neusoft.grpc.proto.demo1.ServicePushDemo.internal_static_TopicOne_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.neusoft.grpc.proto.demo1.ServicePushDemo.internal_static_TopicOne_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.neusoft.grpc.proto.demo1.TopicOne.class, com.neusoft.grpc.proto.demo1.TopicOne.Builder.class);
    }

    // Construct using com.neusoft.grpc.proto.demo1.TopicOne.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      topicId_ = "";

      topicName_ = "";

      xxx_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.neusoft.grpc.proto.demo1.ServicePushDemo.internal_static_TopicOne_descriptor;
    }

    public com.neusoft.grpc.proto.demo1.TopicOne getDefaultInstanceForType() {
      return com.neusoft.grpc.proto.demo1.TopicOne.getDefaultInstance();
    }

    public com.neusoft.grpc.proto.demo1.TopicOne build() {
      com.neusoft.grpc.proto.demo1.TopicOne result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.neusoft.grpc.proto.demo1.TopicOne buildPartial() {
      com.neusoft.grpc.proto.demo1.TopicOne result = new com.neusoft.grpc.proto.demo1.TopicOne(this);
      result.topicId_ = topicId_;
      result.topicName_ = topicName_;
      result.xxx_ = xxx_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.neusoft.grpc.proto.demo1.TopicOne) {
        return mergeFrom((com.neusoft.grpc.proto.demo1.TopicOne)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.neusoft.grpc.proto.demo1.TopicOne other) {
      if (other == com.neusoft.grpc.proto.demo1.TopicOne.getDefaultInstance()) return this;
      if (!other.getTopicId().isEmpty()) {
        topicId_ = other.topicId_;
        onChanged();
      }
      if (!other.getTopicName().isEmpty()) {
        topicName_ = other.topicName_;
        onChanged();
      }
      if (!other.getXxx().isEmpty()) {
        xxx_ = other.xxx_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.neusoft.grpc.proto.demo1.TopicOne parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.neusoft.grpc.proto.demo1.TopicOne) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object topicId_ = "";
    /**
     * <code>string topicId = 1;</code>
     */
    public java.lang.String getTopicId() {
      java.lang.Object ref = topicId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        topicId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string topicId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTopicIdBytes() {
      java.lang.Object ref = topicId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        topicId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string topicId = 1;</code>
     */
    public Builder setTopicId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      topicId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string topicId = 1;</code>
     */
    public Builder clearTopicId() {
      
      topicId_ = getDefaultInstance().getTopicId();
      onChanged();
      return this;
    }
    /**
     * <code>string topicId = 1;</code>
     */
    public Builder setTopicIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      topicId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object topicName_ = "";
    /**
     * <code>string topicName = 2;</code>
     */
    public java.lang.String getTopicName() {
      java.lang.Object ref = topicName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        topicName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string topicName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTopicNameBytes() {
      java.lang.Object ref = topicName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        topicName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string topicName = 2;</code>
     */
    public Builder setTopicName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      topicName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string topicName = 2;</code>
     */
    public Builder clearTopicName() {
      
      topicName_ = getDefaultInstance().getTopicName();
      onChanged();
      return this;
    }
    /**
     * <code>string topicName = 2;</code>
     */
    public Builder setTopicNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      topicName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object xxx_ = "";
    /**
     * <code>string xxx = 3;</code>
     */
    public java.lang.String getXxx() {
      java.lang.Object ref = xxx_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        xxx_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string xxx = 3;</code>
     */
    public com.google.protobuf.ByteString
        getXxxBytes() {
      java.lang.Object ref = xxx_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        xxx_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string xxx = 3;</code>
     */
    public Builder setXxx(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      xxx_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string xxx = 3;</code>
     */
    public Builder clearXxx() {
      
      xxx_ = getDefaultInstance().getXxx();
      onChanged();
      return this;
    }
    /**
     * <code>string xxx = 3;</code>
     */
    public Builder setXxxBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      xxx_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:TopicOne)
  }

  // @@protoc_insertion_point(class_scope:TopicOne)
  private static final com.neusoft.grpc.proto.demo1.TopicOne DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.neusoft.grpc.proto.demo1.TopicOne();
  }

  public static com.neusoft.grpc.proto.demo1.TopicOne getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TopicOne>
      PARSER = new com.google.protobuf.AbstractParser<TopicOne>() {
    public TopicOne parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new TopicOne(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TopicOne> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TopicOne> getParserForType() {
    return PARSER;
  }

  public com.neusoft.grpc.proto.demo1.TopicOne getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

