// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service_push.proto

package com.neusoft.grpc.proto.demo1;

public interface TopicOneOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TopicOne)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string topicId = 1;</code>
   */
  java.lang.String getTopicId();
  /**
   * <code>string topicId = 1;</code>
   */
  com.google.protobuf.ByteString
      getTopicIdBytes();

  /**
   * <code>string topicName = 2;</code>
   */
  java.lang.String getTopicName();
  /**
   * <code>string topicName = 2;</code>
   */
  com.google.protobuf.ByteString
      getTopicNameBytes();

  /**
   * <code>string xxx = 3;</code>
   */
  java.lang.String getXxx();
  /**
   * <code>string xxx = 3;</code>
   */
  com.google.protobuf.ByteString
      getXxxBytes();
}
