// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service_push.proto

package com.neusoft.grpc.proto.demo1;

public interface TopicInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TopicInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ClientInfo clientInfo = 1;</code>
   */
  boolean hasClientInfo();
  /**
   * <code>.ClientInfo clientInfo = 1;</code>
   */
  com.neusoft.grpc.proto.demo1.ClientInfo getClientInfo();
  /**
   * <code>.ClientInfo clientInfo = 1;</code>
   */
  com.neusoft.grpc.proto.demo1.ClientInfoOrBuilder getClientInfoOrBuilder();

  /**
   * <code>string topicName = 2;</code>
   */
  java.lang.String getTopicName();
  /**
   * <code>string topicName = 2;</code>
   */
  com.google.protobuf.ByteString
      getTopicNameBytes();
}
